name: dhydro
channels:
  - conda-forge
dependencies:
  - python=3.9
  - geopandas
  - pandas
  - tqdm
  - pandas
  - plotly
  - numpy
  - Shapely
  - jupyter
  - jupyterlab
  - jupyterlab-plotly-extension
  - netCDF4
# this file serves as a temporary environment for development of the profile-optimizer, until a common hydrolib environment is available