site_name: HYDROLIB documentation
theme:
  name: material
  language: en
  logo: images/HYDROLIB_logo_notext_mono_eroded.svg
  palette:
    - scheme: deltares
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
plugins:
  - search
  - mkdocs-jupyter
  - autorefs
  - table-reader
  - monorepo
  - macros:
      module_name: docs/include/mkdocs-macros/main
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_toc_entry: false
            show_source: true
            show_signature_annotations: true
            heading_level: 3
            show_category_heading: false
            group_by_category: false
          selection:
            inherited_members: false

      custom_templates: templates
      watch:
        - hydrolib
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
repo_url: https://github.com/Deltares/HYDROLIB
repo_name: deltares/HYDROLIB
edit_uri: edit/main/docs/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Deltares/HYDROLIB
      name: Source code
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/Deltares/HYDROLIB
      name: Chat with us on Gitter
copyright: Copyright &copy; 2022 Deltares
extra_css:
  - stylesheets/extra.css

nav:
  - Home: "index.md"
  - How-to: 
      - Installation: "guides/setup.md"
      - Contributing: "guides/contributing.md"
      - Documentation: "guides/documentation.md"
  - Tools:
      - Introduction: "tools/tools_introduction.md"
      - HydroMT-Delft3D FM plugin: "!include ./hydrolib/hydromt_delft3dfm/mkdocs.yml"
  - Reference: 
          - "reference/api.md"
  - Changelog: 
          - "changelog.md"
  

