site_name: HYDROLIB documentation
theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      custom_templates: templates
      watch:
        - _hydrolib
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
repo_url: https://github.com/Deltares/HYDROLIB
edit_uri: edit/main/docs/
repo_name: deltares/HYDROLIB
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Deltares/HYDROLIB
      name: Source code
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/Deltares/HYDROLIB
      name: Chat with us on Gitter
copyright: Copyright &copy; 2021 Deltares

