name: hydrolib

channels:
  - default
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - jupyter
  - spyder
  - pandas
  - openpyxl
  - setuptools
  - matplotlib
  - bokeh
  - pip:
    - hydrolib-core