name: po_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - netCDF4
  - tqdm
  - matplotlib
  - numpy
  - scipy
  - pandas
  - shapely
  - sympy
  - geopandas
  - xarray
  - jupyter
  - plotly
  - pip:
      - hydrolib-core
