name: arcadis
 
channels:
  - defaults

dependencies:
  - python<3.9
  - GDAL<3.5.2
  - rasterio<1.3
  - matplotlib      # BSD / PSF
  - geopandas       # BSD-3 Clause
  - geopy           # MIT License
  - pandas<1.5      # BSD 3-Clause
  - pip
  - pip:
    - -r requirements.txt
