name: arcadis
 
channels:
  - defaults

dependencies:
  - GDAL<3.5.2
  - geopandas       
  - geopy
  - matplotlib   
  - pandas<1.5
  - pip
  - python = 3.7
  - rasterio<1.3
  - pip:
    - -r requirements.txt
