name: ci

on: [push, pull_request]

jobs:
  CI:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.11'
            environment: py311
          - python-version: '3.12'
            environment: py312
          - python-version: '3.13'
            environment: py313
          # - python-version: '3.14'
          #   environment: py314
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          pixi-version: v0.78.0
          cache: true
          environments: ${{ matrix.environment }}

      - name: Check lock file is up to date
        run: pixi lock --check

      - name: Test with pytest
        run: pixi run --environment ${{ matrix.environment }} --locked test

      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

      # - name: Lint
      #   run: pixi run --environment ${{ matrix.environment }} --locked lint

  check-conda-exports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          pixi-version: v0.78.0
          cache: true
          environments: py312

      - name: Regenerate Conda environment exports
        run: pixi run --environment py312 --locked export-conda-environments

      - name: Fail if exported environments are stale
        run: git diff --exit-code -- environment-win-64.yml environment-linux-64.yml
